# Generated by Django 3.2.9 on 2021-11-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('web_url', models.CharField(max_length=200)),
                ('web_name', models.CharField(max_length=200)),
                ('state', models.BooleanField()),
                ('get_date', models.DateTimeField()),
                ('crux_word', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collect_time', models.DateTimeField()),
                ('b_title', models.CharField(max_length=500)),
                ('b_url', models.CharField(max_length=500)),
                ('b_release', models.DateTimeField()),
                ('b_money', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=50)),
                ('b_time', models.DateTimeField()),
                ('notice_type', models.CharField(max_length=50)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bid.collect')),
            ],
        ),
    ]
