# Generated by Django 3.2.9 on 2021-11-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211125_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_id',
            field=models.CharField(default=['1'], max_length=500, null=True),
        ),
    ]
